### ISSUE TITLE
Possible Java bug in CompilerFactory.java

### ISSUE THREAD

**Issue by dynarithmic** [schxslt/schxslt-java#3]
Note:  I found this with a SonarQube check on the code.

Here is a possible bug in CompilerFactory.java when checking for a blank string:

`if (queryBinding == "") {`

A check for a blank string should use `queryBinding.isEmpty()`, or `.equals("")` (plus maybe a check for `null` beforehand).

**Comment by dmj** [comment]
Thanks for reporting!
